### ISSUE TITLE
not compatible with 1.19.3

### ISSUE THREAD

**Issue by ALeX400** [remplerus/AgriGrowth#1]
in the description it states that it is compatible with the following versions:
```java
1.19.4
1.19.3
1.19.2
```
I'm running on version `1.19.3` (because it's a little more optimized) and it tells me that it requires `1.19.2`

**Comment by remplerus** [comment]
![grafik](https://github.com/remplerus/AgriGrowth/assets/44590574/e6c8549d-2cd8-4cff-8a1a-a4a5f56e7c32)
im building against 1.19.3. so without any logs and used versions i can only close this issue.
